apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: testwf-
spec:
  entrypoint: testwf

  templates:
  - name: testwf
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        template: echo
        depends: "B"
        arguments:
          parameters: [{name: message, value: C}]
      - name: Recursive
        template: recurse

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]

  - name: recurse
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: tails                     # keep flipping coins if "tails"
        template: recurse
        when: "{{steps.flip-coin.outputs.result}} == tails"

  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)
